### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by SuperFra** [glumb/kinematics#4]
you can have an example of code in html to test the library?

**Comment by glumb** [comment]
There are some examples in the readme. What specific html examples are you interested in?
I'm using the kinematics in a THREEJS project, which I am going to publish soon. (in 9 month)
![bildschirmfoto 2017-01-29 um 23 16 02](https://cloud.githubusercontent.com/assets/3062564/22408432/ec9e9024-e678-11e6-988a-45ae95a1594b.png)

**Comment by fdiazsmith** [comment]
Any word on the Three.js example? I am having trouble integrating with threejs and  What you have on the screenshot seems to be just what I am looking for.

**Comment by glumb** [comment]
I had a lot of other work todo lately. I will publish the THREE.js demo in a few weeks.

**Comment by caracal7** [comment]
I started to develop similar project for controlling  my 5dof robot arm but your demo looks much more interesting and usable))

**Comment by caracal7** [comment]
One more problem that I need to solve with IK is linear actuators like rails.

**Comment by glumb** [comment]
@caracal7 Some simple approaches You could calculate the closest point on the rail, move the robot there and then just use the IK. Or check if the target is in range and don't move the robot on the rail. Or check if in range, if not, move the robot on the rail one unit in the direction of the closest point on the rail regarding the target, check if in range, repeat.

**Comment by caracal7** [comment]
@glumb Thanks) It is very simple and I think is working solution. At moment it is enough for me but after I want to try to develop modular construction with any combinations of joints and rails. And I also looking for solutions for simultaneous control of several different arm configurations.

**Comment by curtpw** [comment]
I would be very interested in seeing the code for the kinematics three.js demo you posted a screenshot of....

**Comment by glumb** [comment]
🎉 I finally had the time to refactor the robot Gui to a state where it is publishable on GitHub: https://github.com/glumb/robot-gui

See the demo here http://robot.glumb.de/ (does not work on Safari due to some ES6 features. I want to keep it simple and not use a build process or bundler)
