### ISSUE TITLE
How to set joint angles?

### ISSUE THREAD

**Issue by SuperFra** [glumb/kinematics#5]
At first I would to say sorry for my english!
When I get the angles from the inverse function how to set theese angle to my object in three?

**Comment by SuperFra** [comment]
Solved. Just made a mess with the axis. Thanks anyway for your nice work.

**Comment by glumb** [comment]
Thanks! Just for further reference
```js
const x = 10, y = 10, z = 10, a = 10, b = 10, c = 10
angles = RobotKin.inverse(x, y, z, a, b, c)

robotLinks = getRobotLinks() // get some THREEJS geometry....
robotLinks[0].rotation.y = angles[0]
robotLinks[1].rotation.z = angles[1]
[...]
```
