### ISSUE TITLE
Why library limited to 6 DOF?

### ISSUE THREAD

**Issue by caracal7** [glumb/kinematics#6]

**Comment by glumb** [comment]
You can use the library for less than 6 DOF, too.
Problems with more than 6DOF are overdetermined, since there are three dimensions in space + 3 axis of rotations.

**Comment by pranav-ap** [comment]
Hi, 
Do we need to make changes to the library to use a 4 DOF arm or does it simply work? I get the following error.

`Uncaught (in promise) Error: geometry array must have 5 entries`

**Comment by glumb** [comment]
have you tried setting the 5th element of the array to `[0, 0,  0],` so V4 is essentially 0?
