### ISSUE TITLE
Why does y,z of V3 and x,z of V4 be 0 for the kinematics to work?

### ISSUE THREAD

**Issue by pranav-ap** [glumb/kinematics#7]
I'm a beginner, so this is probably a dumb question.
 : )

**Comment by glumb** [comment]
The axis of J3 J4 and J5 must meet in a single point. This requirement is based on how the kinematic is calculated. 

Most industrial robots fulfill this criteria. The Universal Robot however has a wrist with non intersecting axes. Therefore the library can’t be used for UR robots unfortunately.

**Comment by pranav-ap** [comment]
I understand. Thanks!
